# Generated by Django 5.1 on 2024-08-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_alter_cart_cart_id'),
        ('store', '0003_rename_image_product_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='varitions',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(to='store.variation'),
        ),
    ]
