# Generated by Django 5.1 on 2024-08-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_remove_cartitem_varitions_cartitem_variations'),
        ('store', '0003_rename_image_product_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
